# Generated by Django 4.1.7 on 2023-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bathroom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_id', models.IntegerField()),
                ('building_name', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('floor', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('num_toilets', models.IntegerField()),
                ('num_urinals', models.IntegerField()),
                ('num_sinks', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
