# Generated by Django 4.1.7 on 2023-02-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroom',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bathroom',
            name='longitude',
        ),
    ]
