# Generated by Django 4.1.7 on 2023-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bathroom_id', models.IntegerField()),
                ('date', models.DateField()),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cleanliness_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('smell_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comments', models.TextField()),
            ],
        ),
    ]
